### ISSUE TITLE
Sort admin dashboard player list alphabetically

### ISSUE THREAD

**Issue by snorremd** [snorremd/code-monkey-clash#23]
To make it simpler for the admin to find players sort them alphabetically. The list should be re-sorted as new players join.

**Comment by Rajvardhan222** [comment]
Hello, I am new to open source , how can i start contributing to this issue?

**Comment by snorremd** [comment]
> Hello, I am new to open source , how can i start contributing to this issue?

Hi there! Nice that you want to contribute. Making no assumptions of your previous knowledge here, but what you need to do:

1. Fork the repository so you have something to create a PR from
2. Create a branch in your fork (optional) so that you can work on the change
3. Make sure you have bun installed so you can run the project
4. Copy the `.env.example` to `.env` and add a secret value
5. Run the project with `bun run dev`

A local copy of the server should be running.
Now you want to log into the admin panel in one tab. In a different tab sign up some players.

Now edit https://github.com/snorremd/code-monkey-clash/blob/main/src/pages/admin.tsx#L310 so that the sorting uses the player nick instead of score.

To enable sorting when new players are inserted via SSE you should study how it is done for the `scoreboard` logic in https://github.com/snorremd/code-monkey-clash/blob/main/src/client/client.ts and replicate that. Essentially there is an event (you can see it in the network inspector on the admin page) that inserts new player rows. When this event is received by the client we want to sort the player rows.

Once you are happy with your changes create a pull request.

You can see some more details on how to fork and make pull requests in GitHub's own documentation: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by snorremd** [comment]
I decided to tackle this myself as I've not seen anything new in this issue for about a month.
Decided to do some refactoring to avoid sorting logic being very duplicated.
